import { StyleSheet } from '@react-pdf/renderer';

export default StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#263238',
    padding: 5
  },
  mainSection: {
    flexDirection: 'column',
    height: '800px',
    padding: 5,
    margin: 15,
    backgroundColor: '#cfd8dc',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  logoSection: {
    position: 'absolute',
    top: 110,
    width: 280,
    height: 90,
    padding: 20,
    backgroundColor: '#eceff1',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  logo: {
    fontSize: 16,
    letterSpacing: 8,
    padding: 5,
    paddingLeft: 20,
  },
  asesor: {
    fontSize: 11,
    letterSpacing: 4,
    paddingTop: 10,
    textIndent: 22,
  },
  asesorSub: {
    fontSize: 7,
    letterSpacing: 2,
    padding: 2,
    paddingTop: 2,
    textIndent: 20,
  },
  cel: {
    fontSize: 8,
    letterSpacing: 2,
    padding: 2,
    paddingTop: 10,
    textIndent: 20,
  },
  mail: {
    fontSize: 8,
    letterSpacing: 2,
    padding: 2,
    textIndent: 20,
  },
  titulo: {
    fontSize: 16,
    letterSpacing: 1,
    padding: 4,
    backgroundColor: '#546e7a   ',
    color: '#eceff1',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
  },
  clave: {
    fontSize: 8,
    marginTop: 2,
    marginLeft: 8
  },
  rowTitleSection: {
    flexDirection: 'row',
    // height: '280px',
    padding: 2
  },
  precio: {
    fontSize: 15,
    padding: 3,
    backgroundColor: '#546e7a   ',
    color: '#eceff1',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    borderBottomLeftRadius: 6,
  },
  rightSection: {
    width: '280px',
    height: '90px',
    padding: '5px',
    paddingTop: '5px',
    backgroundColor: '#eceff1',
    position: 'absolute',
    left: '260px',
    top: '15px',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 1,
    borderBottomLeftRadius: 1,
  },
  imagenPortada: {
    position: 'absolute',
    top: 90,
    width: '280px',
    height: '240px',
    borderTopLeftRadius: 1,
    borderTopRightRadius: 1,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 1,
  },
  specsSection: {
    position: 'absolute',
    top: 105,
    left: 15,
    height: '240px',
    width: '260px',
    padding: 20,
    backgroundColor: '#eceff1',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 1,
    borderBottomRightRadius: 1,
    borderBottomLeftRadius: 10,
    fontSize: 10,
    letterSpacing: 1,
    lineHeight: 3,
  },
  descripSection: {
    position: 'absolute',
    top: 355,
    left: 15,
    height: '185px',
    width: '525px',
    padding: 12,
    backgroundColor: '#eceff1',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  descripText: {
    fontSize: 11,
    letterSpacing: 1.5,
    lineHeight: 2.5,
  },
  descripTextLarge: {
    fontSize: 6,
    letterSpacing: 1,
    lineHeight: 2,
  },
  bottomImgSection: {
    flexDirection: 'row',
    height: '280px',
    padding: 5
  },
  imagenSegunda: {
    position: 'absolute',
    top: 450,
    left: 15,
    width: '250px',
    height: '210px',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  imagenTercera: {
    position: 'absolute',
    top: 450,
    right: 15,
    width: '250px',
    height: '210px',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  colImgSection: {
    flexDirection: 'column',
    width: 600,
    height: 800,
  },
  rowImgSection: {
    flexDirection: 'row',
    width: 600,
    height: 250,
  },
  img: {
    width: '260px',
    height: '210px',
    padding: 10,
    paddingLeft: 30,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  }
});
